### ISSUE TITLE
技术周刊－20160531

### ISSUE THREAD

**Issue by LoeiFy** [ym-fe/ym-fe.github.io#1]
//...

**Comment by LoeiFy** [comment]
### Mo code, mo problems

http://www.csspurge.com/

You may not know, but your CSS is getting out of control, it may even have a mind of its own. The specificity war is happening right now and you might not even know it.
随着项目功能添加，css 会变得越来越多，css 会失控。文章对比了几家 css 的使用情况

**Comment by zWingz** [comment]
**Fetch_ API介绍**
http://www.w3ctech.com/topic/854
https://github.com/camsong/blog/issues/2

【CSS进阶】伪元素的妙用--单标签之美
http://www.cnblogs.com/coco1s/p/5528393.html

**Comment by Fszer** [comment]
qq 移动浏览器 x5 内核谁用谁知道

http://bbs.mb.qq.com/thread-215666-1-1.html

**Comment by jingzhiMo** [comment]
再次了解一下依赖注入的思想，对于前端
[http://imweb.io/topic/571b567505637d4c67ae3f64](http://imweb.io/topic/571b567505637d4c67ae3f64)

**Comment by Rockergmail** [comment]
《一种SPA（单页面应用）架构》，本文脱离了框架和语言，直接从架构上剖析了SPA，分为前端和后端架构。值得学习。

https://github.com/livoras/blog/issues/3
